apiVersion: v1
kind: Pod
metadata: 
  name: myanypod
  labels: 
    app: myapp

spec: 
  containers: 
  - name: myapp-container
    image: busybox
    command: ["sh", "-c", " sleep 36000 && exit 0" ] 
